// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6U8sJrJtCRPggTyipkwpwXiAasKNUhMs',
    appId: '1:433533131535:web:9b04c9d223971cc3907c7a',
    messagingSenderId: '433533131535',
    projectId: 'flutterfirenajib',
    authDomain: 'flutterfirenajib.firebaseapp.com',
    storageBucket: 'flutterfirenajib.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYLD11T8-tjqKn2apnJ6uCVkU9RJirlh0',
    appId: '1:433533131535:android:d9a28e682e8775d6907c7a',
    messagingSenderId: '433533131535',
    projectId: 'flutterfirenajib',
    storageBucket: 'flutterfirenajib.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxRhS8MEdrPN1Isq-bqiJ3bynKt5ZednY',
    appId: '1:433533131535:ios:51855e43e26ebe85907c7a',
    messagingSenderId: '433533131535',
    projectId: 'flutterfirenajib',
    storageBucket: 'flutterfirenajib.appspot.com',
    iosBundleId: 'com.example.flutterlist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxRhS8MEdrPN1Isq-bqiJ3bynKt5ZednY',
    appId: '1:433533131535:ios:6bbcae5246f46099907c7a',
    messagingSenderId: '433533131535',
    projectId: 'flutterfirenajib',
    storageBucket: 'flutterfirenajib.appspot.com',
    iosBundleId: 'com.example.flutterlist.RunnerTests',
  );
}
